### ISSUE TITLE
WebAPI faltando referência à Microsoft.AspNet.WebApi.WebHost

### ISSUE THREAD

**Issue by thiagoloureiro** [DevPartner-BR/backend-projects-test#1]
Faltando pacote nuget **Microsoft.AspNet.WebApi.WebHost** no projeto WebAPI

`Install-Package Microsoft.AspNet.WebApi.WebHost`

**Comment by carloshenriqueribeiro** [comment]
Boa Thiago!

Carlos Ribeiro
